apiVersion: v1
kind: ConfigMap
metadata:
  name: web-contents
data:
  index.html: |
    Hello World from Staging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
          - name: web-contents
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
      volumes:
        - name: web-contents
          configMap:
            name: web-contents

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80